# Generated by Django 5.2.7 on 2025-11-04 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita_veterinaria',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
